# 毕业论文
## 前置数据处理：使用`pygrib`读取FNL
`Read FNL file Using pygrib`
---
*@author: Evan*\
*@date: 2023-10-07*

In [1]:
import pygrib as pg
import numpy as np

# silence the warning note
import warnings
warnings.filterwarnings("ignore")

import sys
sys.path.append('../../src/')
from namelist import *

# 逐步骤读取信息

In [11]:
grb = pg.open(demodir + 'fnl_20140616_00_00.grib2')

读取文件数据

In [4]:
temp = grb.select(name='Temperature')
temp

[3:Temperature:K (instant):regular_ll:isobaricInhPa:level 1000 Pa:fcst time 0 hrs:from 201406160000,
 9:Temperature:K (instant):regular_ll:isobaricInhPa:level 2000 Pa:fcst time 0 hrs:from 201406160000,
 15:Temperature:K (instant):regular_ll:isobaricInhPa:level 3000 Pa:fcst time 0 hrs:from 201406160000,
 21:Temperature:K (instant):regular_ll:isobaricInhPa:level 5000 Pa:fcst time 0 hrs:from 201406160000,
 27:Temperature:K (instant):regular_ll:isobaricInhPa:level 7000 Pa:fcst time 0 hrs:from 201406160000,
 33:Temperature:K (instant):regular_ll:isobaricInhPa:level 10000 Pa:fcst time 0 hrs:from 201406160000,
 42:Temperature:K (instant):regular_ll:isobaricInhPa:level 15000 Pa:fcst time 0 hrs:from 201406160000,
 50:Temperature:K (instant):regular_ll:isobaricInhPa:level 20000 Pa:fcst time 0 hrs:from 201406160000,
 58:Temperature:K (instant):regular_ll:isobaricInhPa:level 25000 Pa:fcst time 0 hrs:from 201406160000,
 66:Temperature:K (instant):regular_ll:isobaricInhPa:level 30000 Pa:fcst time 0 

In [5]:
temp_sel = temp[0]
data = temp_sel.values

In [6]:
print(data.shape)
data

(181, 360)


array([[241.7, 241.7, 241.7, ..., 241.7, 241.7, 241.7],
       [241.6, 241.6, 241.6, ..., 241.6, 241.6, 241.6],
       [241.5, 241.5, 241.5, ..., 241.5, 241.5, 241.5],
       ...,
       [189.7, 189.7, 189.7, ..., 189.7, 189.7, 189.7],
       [189.9, 189.9, 189.9, ..., 189.9, 189.9, 189.9],
       [189.9, 189.9, 189.9, ..., 189.9, 189.9, 189.9]])

In [12]:
messages = grb.select()
# 获取消息在文件中的位置
offset = temp_sel.messagenumber - 1
grb.close()

# 修改数据，写入原变量

In [2]:
# open one grib2 file
grb = pg.open(demodir + 'fnl_20140616_00_00.grib2')
# select temperature as you wish
var = grb.select(name='Temperature')
# select the first message and data in temperatures
selected_var = var[0]
data = selected_var.values
# get the message number
messages = grb.select()
offset = selected_var.messagenumber - 1
grb.close()

In [14]:
var[0].values

array([[241.7, 241.7, 241.7, ..., 241.7, 241.7, 241.7],
       [241.6, 241.6, 241.6, ..., 241.6, 241.6, 241.6],
       [241.5, 241.5, 241.5, ..., 241.5, 241.5, 241.5],
       ...,
       [189.7, 189.7, 189.7, ..., 189.7, 189.7, 189.7],
       [189.9, 189.9, 189.9, ..., 189.9, 189.9, 189.9],
       [189.9, 189.9, 189.9, ..., 189.9, 189.9, 189.9]])

In [15]:
var[0].values=np.zeros([181,360])

创建新的grib2文件

In [17]:
# open the output grib2 file
grbout = open(demodir + 'grbout.grib2', 'wb')
# write all messages from temperature (including values)
for i in range(len(var)):
    msg = var[i].tostring()
    grbout.write(msg)
grbout.close()

检查是否成功修改

In [18]:
test = pg.open(demodir + 'grbout.grib2')
test_var = test.select()
test_var[0].values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])